name: Publish to TestPyPI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/sphinxcontrib-images

    permissions:
      # Needed for trusted publishing
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: pip

      - name: Install pypa/build
        run: python -m pip install build

      - name: Build a binary wheel and a source tarball
        run: python -m build

      - uses: actions/upload-artifact@v4
        with:
          name: sphinxcontrib-images
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
